### ISSUE TITLE
any thoughts on providing english translations? 

### ISSUE THREAD

**Issue by bboydflo** [sylvainpolletvillard/pwa-cookbook#3]
thanks for this. I think it would be awesome to have an english translation as well.

**Comment by sylvainpolletvillard** [comment]
Hi @bboydflo 

My friend @yostane already started to translate this cookbook in english. You can already see our progress here: https://github.com/sylvainpolletvillard/pwa-cookbook/tree/master/static/pages/en

Expect english translation to come soon in the website too :)

**Comment by yostane** [comment]
Hi @bboydflo,
Thanks for the comment, I just published the english translation 🎉.
Please do not hesitate to provide your feedback and open new issues 👍
